# CI build for unreal projects

build_linux_task:
  timeout_in: 180m
  container:
    image: adamrehn/ue4-engine:4.19
    cpu: 8
    memory: 24G

  script: 
    - /home/ue4/UnrealEngine/Engine/Build/BatchFiles/Linux/Build.sh MyProjectEditor Linux Development -project="$CIRRUS_WORKING_DIR/HelloFly.uproject"