# CI build for unreal projects

build_linux_task:
  timeout_in: 180m
  container:
    image: srl3gx/ubuntu:18.04
    cpu: 8
    memory: 24G
  
  env:
    CACHE_INDEX: 0
    UNREAL_VERSION: 4.18
    UNREAL_DEPLOY_SSH_KEY: ENCRYPTED[9a361416afe386e8dffb8c5cc94c8e62e9d21ba30913221822df37cbdbdbc849a9ae738b0e01dd72596770f7ca68f109]
    PROJECT_NAME: Blocks
    PROJECT_DIR: /tmp/airsim/Unreal/Environments/Blocks

  before_script:
    - sudo apt-get update -y
    - 'which ssh-agent || ( sudo apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - sudo apt-get install -y git wget rsync

  airsim_script:
    - cd ..
    - git clone https://github.com/Microsoft/AirSim.git airsim
    - cd airsim
    - ./setup.sh
    - ./build.sh

  unreal_engine_script:
    - cd ..
    - ssh-agent bash -c 'ssh-add <(echo "$UNREAL_DEPLOY_SSH_KEY"); git clone -b $UNREAL_VERSION git@github.com:sreejithkrishnanr/UnrealEngine.git ur4'
    - cd ur4
    - ./Setup.sh
    - ./GenerateProjectFiles.sh

  script: 
    - cd ../ur4
    - mkdir "$PROJECT_DIR/Build"
    - Engine/Build/BatchFiles/Linux/Build.sh ShaderCompileWorker Linux Development
    - Engine/Build/BatchFiles/RunUAT.sh BuildCookRun -Project="$PROJECT_DIR/${PROJECT_NAME}.uproject" -NoP4 -Distribution -TargetPlatform=Linux -Platform=Linux -ClientConfig=Shipping -ServerConfig=Shipping -Cook -Build -Stage -Pak -Archive -ArchiveDirectory="$PROJECT_DIR/Build" -Rocket -Prereqs -Package
    - tree -d $PROJECT_DIR/Build