# global default
build_task:
  container:
    image: python:2.7
    cpu: 8
    memory: 16G
  
  env:
    UNREAL_VERSION: 4.18
    UR_SSH_KEY: ENCRYPTED[9a361416afe386e8dffb8c5cc94c8e62e9d21ba30913221822df37cbdbdbc849a9ae738b0e01dd72596770f7ca68f109]

  before_script:
    - 'which ssh-agent || ( sudo apt-get update -y && sudo apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$UR_SSH_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  
  unrealengine_cache:
    folder: ur4
    fingerprint_script: echo $UNREAL_VERSION
    populate_script: git clone -b $UNREAL_VERSION git@github.com:sreejithkrishnanr/UnrealEngine.git ur4 && cd ur4 && ./Setup.sh && cd ..

  script: 
    - cd ur4
    - ./GenerateProjectFiles.sh
    - make -j32
    - cd ..