# CI build for unreal projects

build_linux_task:
  timeout_in: 180m
  container:
    image: srl3gx/ubuntu:18.04
    cpu: 8
    memory: 16G
  
  env:
    CACHE_INDEX: 0
    UNREAL_VERSION: 4.18
    UNREAL_DEPLOY_SSH_KEY: ENCRYPTED[9a361416afe386e8dffb8c5cc94c8e62e9d21ba30913221822df37cbdbdbc849a9ae738b0e01dd72596770f7ca68f109]

  before_script:
    - sudo apt-get update -y
    - 'which ssh-agent || ( sudo apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - sudo apt-get install -y git
  
  unrealengine_cache:
    folder: ur4
    fingerprint_script: 
      - echo $UNREAL_VERSION
      - echo $CACHE_INDEX
    populate_script: 
      - ssh-agent bash -c 'ssh-add <(echo "$UNREAL_DEPLOY_SSH_KEY"); git clone -b $UNREAL_VERSION git@github.com:sreejithkrishnanr/UnrealEngine.git ur4'

  script: 
    - cd ur4
    - ./Setup.sh
    - ./GenerateProjectFiles.sh
    - Engine/Build/BatchFiles/Linux/Build.sh HelloFly Linux Development "$CIRRUS_WORKING_DIR/HelloFly.uproject"
    - ls
    - cd ..