version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
        environment:
           TZ: "America/Los_Angeles"
    environment:
      TZ: "America/Los_Angeles"
    steps:
      - checkout:
          path: project
      - run: apt-get update
      - run: apt-get install -y sudo
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
      - run:
          name: Install dependencies
          command: |
              sudo apt install -y git build-essential clang-3.9
      - run:
          name: Clone unreal engine
          command: git clone -b 4.18 git@github.com:EpicGames/UnrealEngine.git
      - run:
          name: Build unreal engine
          command: |
              cd UnrealEngine
              ./Setup.sh
              ./GenerateProjectFiles.sh
              make
              cd ..
      - run:
          name: Build project
          command: |
              mkdir project/Build
              mono Engine/Binaries/DotNET/AutomationTool.exe -ScriptsForProject=project/HelloFly.uproject BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project=project/HelloFly.uproject -cook -stage -archive -archivedirectory=project/Build -package -clientconfig=Development -ue4exe=UE4Editor -pak -prereqs -nodebuginfo -targetplatform=Linux -build -utf8output